site_name: JOAN Simulator Documentation
theme: readthedocs


nav:
    - Home: 'index.md'
    - Setup:
      - Setup on Windows: setup-carla-windows.md
      - Setup on Linux: setup-carla-linux.md
      - Create your own JOAN project: setup-create-joan-project.md
      - Setup and run your JOAN project: setup-run-joan.md

    - How to use:
      - Unreal editor(under construction): how-to-unreal.md
      - Source Control (Git): how-to-git.md
      - JOAN (under construction): how-to-joan.md

    - Contributing:
      - Guidelines: contributing-guidelines.md
      - Coding Standard: contributing-coding-standard.md

markdown_extensions:
  - admonition