site_name: JOAN Simulator Documentation
theme: readthedocs


nav:
    - Home: 'index.md'
    - Setup:
      - Setup on Windows: setup-carla-windows.md
      - Setup on Linux: setup-carla-linux.md
      - Setup JOAN: setup-joan.md

    - How to use:
      - JOAN (under construction): how-to-joan.md
      - Unreal editor (under construction): how-to-unreal.md
      - Source Control (Git): how-to-git.md

    - JOAN:
      - JOAN structure: joan-structure.md
      - Create custom modules: joan-create-module.md

    - Contributing:
      - Guidelines: contributing-guidelines.md
      - Coding Standard: contributing-coding-standard.md

markdown_extensions:
  - admonition
  - attr_list