site_name: JOAN Simulator Documentation
theme: readthedocs


nav:
    - Home: 'index.md'
    - Setup:
      - Setup on Windows: setup-carla-windows.md
      - Setup on Linux: setup-carla-linux.md
      - Setup JOAN: setup-joan.md

    - How to use:
      - Unreal editor (under construction): how-to-unreal.md
      - Source Control (Git): how-to-git.md
      - 'JOAN (under construction)':
        - Add your own module: how-to-add-module.md
        - Starting JOAN (workflow): how-to-workflow.md
        - Settings: how-to-settings.md
        - State Machine: how-to-state-machine.md

    - Contributing:
      - Guidelines: contributing-guidelines.md
      - Coding Standard: contributing-coding-standard.md

markdown_extensions:
  - admonition
  - attr_list
  - inline_graphviz