site_name: JOAN Simulator Documentation
theme: readthedocs


nav:
    - Home: 'index.md'
    - Setup:
      - Setup on Windows: setup-carla-windows.md
      - Setup on Linux: setup-carla-linux.md
      - Create your own JOAN project: setup-create-joan-project.md
      - Setup and run your JOAN project: setup-run-joan.md

    - How to use JOAN:
      - Workflow: joan-workflow.md
      - Adding modules: joan-adding-modules.md

    - Contributing:
      - Guidelines: contributing-guidelines.md
      - Coding Standard: contributing-coding-standard.md

markdown_extensions:
  - admonition